name: Deploy GitHub Pages

on:
  push:
    branches:
      - "master"

env:
  PYTHON_VERSION: 3.12.6

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: install obsidian-blog
        run: pip install obsidian-blog

      - name: build static site
        run: obsidian-blog

      - name: Add gh-pages CNAME
        run: echo ${{ secrets.CNAME }} > .build/CNAME

      - uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: .build
